package commonresources_test

import "AnimeunityCLI/packages/commonresources"

var (
	original = []commonresources.AnimePageStruct{
		{
			"200",
			"https://animeunity.it/anime.php?id=200",
			"HIGH SCHOOL DXD",
			[]string{
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_01_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_01_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_01_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"666",
			"https://animeunity.it/anime.php?id=666",
			"HIGH SCHOOL DXD OVA",
			[]string{
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_OAV_02_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_OAV_01_SUB_ITA.mp4",
			},
			true,
		}, {
			"203",
			"https://animeunity.it/anime.php?id=203",
			"HIGH SCHOOL DXD NEW",
			[]string{
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"205",
			"https://animeunity.it/anime.php?id=205",
			"HIGH SCHOOL DXD BORN",
			[]string{
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"665",
			"https://animeunity.it/anime.php?id=665",
			"HIGH SCHOOL DXD BORN: YOMIGAERANAI FUSHICHOU",
			[]string{
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighSchoolDxDBorN_OAV_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"667",
			"https://animeunity.it/anime.php?id=667",
			"HIGH SCHOOL DXD NEW: OPPAI, TSUTSUMIMASU!",
			[]string{
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_OAV_SUB_ITA.mp4",
			},
			false,
		}, {
			"208",
			"https://animeunity.it/anime.php?id=208",
			"HIGH SCHOOL DXD HERO",
			[]string{
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_01_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_00_SUB_ITA.mp4",
			},
			false,
		},
	}





	correct = []commonresources.AnimePageStruct{
		{
			"200",
			"https://animeunity.it/anime.php?id=200",
			"HIGH SCHOOL DXD",
			[]string{
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_Ep_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"666",
			"https://animeunity.it/anime.php?id=666",
			"HIGH SCHOOL DXD OVA",
			[]string{
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_OAV_02_SUB_ITA.mp4",
				"https://www.animeunityserver21.cloud/DDL/Anime/HighSchoolDxD/HighSchoolDxD_OAV_01_SUB_ITA.mp4",
			},
			true,
		}, {
			"203",
			"https://animeunity.it/anime.php?id=203",
			"HIGH SCHOOL DXD NEW",
			[]string{
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_Ep_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"205",
			"https://animeunity.it/anime.php?id=205",
			"HIGH SCHOOL DXD BORN",
			[]string{
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighschoolDXDBorn_Ep_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"665",
			"https://animeunity.it/anime.php?id=665",
			"HIGH SCHOOL DXD BORN: YOMIGAERANAI FUSHICHOU",
			[]string{
				"https://www.animeunityserver54.cloud/DDL/Anime/HighschoolDXDBorn/HighSchoolDxDBorN_OAV_01_SUB_ITA.mp4",
			},
			false,
		}, {
			"667",
			"https://animeunity.it/anime.php?id=667",
			"HIGH SCHOOL DXD NEW: OPPAI, TSUTSUMIMASU!",
			[]string{
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDNew/HighSchoolDxDNew_OAV_SUB_ITA.mp4",
			},
			false,
		}, {
			"208",
			"https://animeunity.it/anime.php?id=208",
			"HIGH SCHOOL DXD HERO",
			[]string{
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_12_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_11_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_10_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_09_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_08_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_07_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_06_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_05_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_04_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_03_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_02_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_01_SUB_ITA.mp4",
				"https://www.animeunityserver96.cloud/DDL/Anime/HighSchoolDxDHero/HighSchoolDxDHero_Ep_00_SUB_ITA.mp4",
			},
			false,
		},
	}
)
